# Generated by Django 5.1.1 on 2024-09-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='password',
            field=models.CharField(default=models.CharField(max_length=200), max_length=200),
        ),
    ]
